version: 3
service:
  loadgen:
    container_name: wsgi-load-generation
    build:
      context: ./loadgen
    image: wsgi_benchmark_loadgen:latest
    ports:
      9808:9808
    networks:
      - wsgi-benchmark
    volumes:
      - benchmarkdata:/home/gen/wsgi_benchmark

  wsgi-servers:
    container_name: wsgi-servers
    build:
      context: ./wsgi-servers
    image: wsgi_benchmark_servers:latest
    ports:
      9808:9808
    networks:
      - wsgi-benchmark
    volumes:
      - benchmarkdata:/home/www/wsgi_benchmark

networks:
    wsgi-benchmark:
        driver: bridge

volumes:
  benchmarkdata:

    